nginx:
  build: nginx/
  links:
    - php:php
  ports:
   - "80:80"
  volumes:
   - nginx/data:/var/www
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: project_b
php:
  build: php/
  expose:
   - "9000"
  links:
   - mysql:mysql
  volumes:
   - nginx/data:/var/www
