nginx:
  build: nginx/
  links:
    - php:php
  ports:
   - "80:80"
  volumes:
   - nginx/data:/var/www
redis:
  build: redis/
  expose:
   - "6379"
  volumes:
   - redis/data:/var/lib/redis
php:
  build: php/
  expose:
   - "9000"
  links:
   - redis:redis
  volumes:
   - nginx/data:/var/www
